#! /bin/bash
# ./PPD --sync
DATE=`date +%Y%m%d_%H%M`

export VALGRIND="valgrind -v --tool=memcheck --leak-check=yes  --show-reachable=yes --error-limit=no --num-callers=20  --freelist-vol=20000000 "

export LD_LIBRARY_PATH=${MYGCC}lib64

$VALGRIND --log-file=memcheck-$DATE Debug/Oxyz3d.exe -lua -load "toto.oxyz" --sync $*
